[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@chainlink/contracts/=lib/chainlink-evm/contracts/",
  "@chainlink/contracts-ccip/contracts/=lib/chainlink-ccip/contracts/chains/evm/contracts/",
  "@chainlink/local/=lib/chainlink-local/", 
  "@chainlink/chainlink-ccip/=lib/chainlink-ccip/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
